on:
  workflow_dispatch:
  push:
    paths:
    - Dockerfile
    - '.github/workflows/**'

jobs:
  build-shinyproxy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Free disk space on Ubuntu Runner 🔧
      uses: jlumbroso/free-disk-space@main
      with:
        # frees about 6 GB, warning: may remove required tools
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/shinyproxy-kth
        tags: |
          type=raw,value=1.0.${{ github.run_number }},priority=1000
          type=ref,event=branch
          type=sha
          type=raw,value=latest
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

#    -
#      name: Login to DockerHub
#      uses: docker/login-action@v1 
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - # https://github.com/docker/login-action#azure-container-registry-acr
#      name: Login to ACR
#      uses: docker/login-action@v1
#      with:
#        registry: kthregistry.azurecr.io
#        username: ${{ secrets.AZURE_CLIENT_ID }}
#        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - # https://github.com/docker/metadata-action
      name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

#    - # https://github.com/docker/build-push-action/blob/master/docs/advanced/copy-between-registries.md
#      name: Push Image to multiple registries
#      uses: akhilerm/tag-push-action@v2.0.0
#      with:
#        src: ghcr.io/${{ github.repository_owner }}/shinyproxy-kth:latest
#        dst: |
#          kthregistry.azurecr.io/${{ github.repository_owner }}/shinyproxy-kth:latest
#          kth-library/shinyproxy-kth:latest

